name: Artifacts for the RocketMod.Unturned Module

on:
  create:
    tags:
      - "*"

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        name: Setup .NET
        with:
          dotnet-version: 7.x

      - name: Build
        run: dotnet build ./Rocket.Unturned/Rocket.Unturned.csproj \
          /p:RocketModVersion=${{ github.ref_name }} \
          /p:CreateRocketModUnturnedModuleArtifacts=true \
          -c Release \
          -f net461

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: "./Rocket.Unturned/Rocket.Unturned.Module.zip"
          if-no-files-found: error

  Release:
    needs: [Build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./build/

      - name: Create Release & Upload Assets
        uses: ncipollo/release-action@v1
        with:
          name: v${{ github.ref_name }}
          tag: v${{ github.ref_name }}
          artifacts: "./build/Rocket.Unturned.Module.zip"
          token: ${{secrets.PAT}}
          prerelease: false
          allowUpdates: true